function listItems(items, render) {
  if (!items?.length) {
    return "- None";
  }

  return items.map(render).join("\n");
}

function validationSummary(validation) {
  if (!validation) {
    return "Validation has not run.";
  }

  if (validation.skipped) {
    return validation.summary;
  }

  return listItems(validation.results, (result) => (
    `- ${result.status.toUpperCase()}: \`${result.command}\` (${result.durationMs}ms)`
  ));
}

function reviewSummary(review) {
  if (!review) {
    return "Review has not run.";
  }

  if (!review.findings?.length) {
    return review.summary;
  }

  return listItems(review.findings, (finding) => (
    `- ${finding.severity.toUpperCase()}: ${finding.title} - ${finding.body}`
  ));
}

export function buildPullRequestTitle(workflow) {
  const issue = workflow.planningInput.issue;
  return `Fix #${issue.number}: ${issue.title}`;
}

export function buildPullRequestBody(workflow) {
  const issue = workflow.planningInput.issue;
  const changedFiles = workflow.diff?.changedFiles || [];

  return [
    "## Summary",
    workflow.implementation?.summary || workflow.plan.issueSummary || "AI-assisted implementation.",
    "",
    "## Issue",
    issue.url ? `- ${issue.url}` : `- #${issue.number}`,
    "",
    "## Plan",
    listItems(workflow.plan.implementationPlan, (item) => `- ${item}`),
    "",
    "## Changed Files",
    listItems(changedFiles, (file) => `- ${file.status}: \`${file.path}\``),
    "",
    "## Validation",
    validationSummary(workflow.validation),
    "",
    "## AI Review",
    reviewSummary(workflow.review),
    "",
    "## Notes",
    "- Generated by AI SDE Workflow.",
    "- Human review and manual merge are required."
  ].join("\n");
}
