import { mkdir, writeFile } from "node:fs/promises";
import path from "node:path";

function candidateFilesFrom(workflow) {
  const searchMatchFiles = workflow.repositoryInspection?.searchMatches?.map((match) => match.path) || [];
  const planFiles = workflow.plan.affectedAreas || [];

  return [...new Set([...searchMatchFiles, ...planFiles])]
    .filter((file) => file && file !== "To be determined after repository checkout")
    .slice(0, 20);
}

function validationCommandsFrom(workflow) {
  const inspectionCommands = workflow.repositoryInspection?.validationCommands || [];

  if (inspectionCommands.length) {
    return inspectionCommands;
  }

  return workflow.plan.validationCommands || [];
}

export async function runMockImplementation({ workflow }) {
  const candidateFiles = candidateFilesFrom(workflow);
  const validationCommands = validationCommandsFrom(workflow);
  const implementation = {
    provider: "mock",
    applied: false,
    summary: "Mock implementation completed. No code changes were applied.",
    candidateFiles,
    plannedChanges: workflow.plan.implementationPlan || [],
    validationCommands,
    changedFiles: [],
    diffSummary: "No diff generated by mock implementation provider."
  };

  if (workflow.workspace?.path) {
    const outputPath = path.join(workflow.workspace.path, "implementation.json");
    await mkdir(workflow.workspace.path, { recursive: true });
    await writeFile(outputPath, `${JSON.stringify(implementation, null, 2)}\n`, "utf8");
    implementation.outputPath = outputPath;
  }

  return implementation;
}
