import { mkdir, writeFile } from "node:fs/promises";
import path from "node:path";
import { candidateFilesFromWorkflow, validationCommandsFromWorkflow } from "./implementationContext.js";

export async function runMockImplementation({ workflow }) {
  const candidateFiles = candidateFilesFromWorkflow(workflow);
  const validationCommands = validationCommandsFromWorkflow(workflow);
  const implementation = {
    provider: "mock",
    applied: false,
    summary: "Mock implementation completed. No code changes were applied.",
    candidateFiles,
    plannedChanges: workflow.plan.implementationPlan || [],
    validationCommands,
    changedFiles: [],
    diffSummary: "No diff generated by mock implementation provider."
  };

  if (workflow.workspace?.path) {
    const outputPath = path.join(workflow.workspace.path, "implementation.json");
    await mkdir(workflow.workspace.path, { recursive: true });
    await writeFile(outputPath, `${JSON.stringify(implementation, null, 2)}\n`, "utf8");
    implementation.outputPath = outputPath;
  }

  return implementation;
}
